apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: nada
  name: nada-update-po-teams-dataset
  namespace: nada
spec:
  image: {{ image }}
  schedule: "10 5 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backoffLimit: 2
  envFrom:
    - secret: nada-data-analyse-sa
  resources:
    request:
      cpu: 10m
      memory: 128Mi
    limit:
      cpu: 100m
      memory: 256Mi
